# Generated by Django 3.2.14 on 2022-08-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetInfo',
        ),
    ]
