# Generated by Django 3.2.14 on 2022-08-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_delete_budgetinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planned_budget', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
