# Generated by Django 3.2.14 on 2022-08-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_categorie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('SV', 'Saving'), ('SP', 'Spending'), ('IN', 'Invest')], default='SV', max_length=2),
        ),
    ]
