# Generated by Django 3.2.14 on 2023-01-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_reason',
            field=models.CharField(choices=[('Necessary', 'Necessary'), ('Needed', 'Needed'), ('Freelancing', 'Freelancing')], default='Salary', max_length=255),
        ),
    ]
