# Generated by Django 3.2.14 on 2023-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_expense_expense_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_reason',
            field=models.CharField(choices=[('Necessary', 'Necessary'), ('Needed', 'Needed'), ('luxury', 'luxury')], default='Salary', max_length=255),
        ),
    ]
