# Generated by Django 3.2.14 on 2023-01-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230128_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='planned_amount',
        ),
    ]
