# Generated by Django 3.2.14 on 2023-01-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230128_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Paypal', 'Paypal')], default='Card', max_length=255),
        ),
    ]
