# Generated by Django 3.2.14 on 2023-01-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_mode',
            field=models.CharField(choices=[('TFL', 'TFL'), ('Go Cars', 'Go Cars')], default='Go Cars', max_length=255),
        ),
    ]
