# Generated by Django 3.2.14 on 2023-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_expense_expense_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_mode',
            field=models.CharField(choices=[('TFL', 'TFL'), ('Go Cars', 'Go Cars'), ('Trainline', 'Trainline')], default='Go Cars', max_length=255),
        ),
    ]
