# Generated by Django 3.2.14 on 2023-01-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tag',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
    ]
