# Generated by Django 3.2.14 on 2023-02-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_expense_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_mode',
        ),
    ]
