# Generated by Django 3.2.14 on 2023-03-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_expense_expense_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(default='Amex', on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
