# Generated by Django 3.2.14 on 2023-03-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_expense_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
