# Generated by Django 3.2.14 on 2023-06-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_expense_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='end_balance',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='saved_amount',
        ),
    ]
