# Generated by Django 3.2.14 on 2023-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20230611_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
