# Generated by Django 3.2.14 on 2023-06-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20230611_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default='Ian', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default='Ian', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default='Ian', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
