# Generated by Django 3.2.14 on 2023-12-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20231127_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_saving',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SavingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=1)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='In Progress', max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='saving_area_icons/')),
                ('user', models.ForeignKey(default='Ian', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='saving_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.savingarea'),
        ),
        migrations.AddField(
            model_name='budget',
            name='saving_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.savingarea'),
        ),
        migrations.AddField(
            model_name='category',
            name='saving_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.savingarea'),
        ),
        migrations.AddField(
            model_name='expense',
            name='saving_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.savingarea'),
        ),
        migrations.AddField(
            model_name='tag',
            name='saving_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.savingarea'),
        ),
    ]
