# Generated by Django 3.2.14 on 2023-12-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20231226_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingarea',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
