# Generated by Django 3.2.14 on 2023-12-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_savingarea_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingarea',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
